#!/system/bin/sh

useragent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3"
download(){
# $1 = url
# $2 = local path
# lets see that curl exits successfully
until /system/bin/curl -s -k -L -A "$useragent" -o "$2" "$1" ;do
 sleep 25
done
}

initfile="/system/etc/init.d/42mad"

if ! [[ -f "$initfile" ]] ;then
 mkdir -p /data/local/madromlogs/
 mount -o remount,rw /system
 download https://raw.githubusercontent.com/Map-A-Droid/MAD-ATV/master/42mad "$initfile" && chmod +x /system/etc/init.d/*
 sleep 5
 /system/bin/sh -x "$initfile" 2>"/data/local/madromlogs/42mad.log"
fi
